### ISSUE TITLE
get-devicelist.ps1 error line 231 invoking the get-data function

### ISSUE THREAD

**Issue by jzcmyz** [dell/OpenManage-Enterprise#161] opened 2021-02-01 06:59 UTC
Line 195 in the function has an invalid uri... 

This line ...
      $NextLinkData = Invoke-RestMethod -Uri "https://$($IpAddress)$($NextLinkUrl)" -Method Get -Credential $Credentials `
        -ContentType $Type -SkipCertificateCheck

needs to be changed to 
      $NextLinkData = Invoke-RestMethod -Uri "$($NextLinkUrl)" -Method Get -Credential $Credentials `
        -ContentType $Type -SkipCertificateCheck

**Comment by grantcurell** [comment] 2021-02-02 20:25
@jzcmyz - sorry, I'm a bit late to the party. Checking it out now

**Comment by grantcurell** [comment] 2021-02-02 22:02
@jzcmyz I tested on Get-Alerts.ps1 because I didn't have enough devices to force paging, but the Get-Data function in both is identical. Screenshot below - it looks like the url is correct, but I may be missing something. Is there an error you're seeing that prompted you to investigate?

![image](https://user-images.githubusercontent.com/35169230/106668263-0fc54700-6578-11eb-8d8c-3d45d2b80834.png)

**Comment by jzcmyz** [comment] 2021-02-03 00:46
Hello Grant
We have more than 50 devices.
This is the error I see..

![2021-02-03 11_35_02-Clipboard](https://user-images.githubusercontent.com/3168688/106681647-03db9280-6615-11eb-8ba5-279b113713d0.png)

This shows the $nextlinkurl variable

![2021-02-03 11_41_54-Clipboard](https://user-images.githubusercontent.com/3168688/106681707-240b5180-6615-11eb-86b1-e9f7ce5475c0.png)

**Comment by grantcurell** [comment] 2021-02-03 02:40
@jzcmyz 

1. I cannot tell you how appreciative I am of the fact that you ran it down to the line in question. It's rare I get that sort of precision in here
2. This might actually be a bug in the API itself. I just did a diff on the get-data function and confirmed they are identical across both files just to make sure I didn't fat finger a copy paste.

I'll investigate more tomorrow. I'll have to see if I can figure out a way to dig into this since I don't have enough devices to force this but just looking at your screenshot vs mine it looks like NextLinkUrl across the two API calls has inconsistent returns.

Thanks for reporting this - really appreciate it.

**Comment by grantcurell** [comment] 2021-02-03 20:50
@jzcmyz apologies - GitHub autoclosed when I PR'd with the word "Fix" (hate that it does that)

I found the issue and patched it. There was a minor bug in the Get-Data function. `BaseUri` wasn't actually being used in the code - it was always undefined which PowerShell was leaving as blank. It only manifested in get-devicelist.ps1 because in the outer scope BaseUri was defined.

Let me know if the problem is fixed for you with the patch.

**Comment by grantcurell** [comment] 2021-02-04 21:06
@jzcmyz - going to close this out but feel free to reopen it if this didn't fix your problem.

**Closed by grantcurell** 2021-02-04 21:06 UTC
Labels: bug

**Comment by jzcmyz** [comment] 2021-02-06 00:04
Hello Grant
I can confirm the issue is resolved.
Thanks for your help with this
