### ISSUE TITLE
Need a script to discover and add a server to a certain group

### ISSUE THREAD

**Issue by vmallemp** [dell/OpenManage-Enterprise#49] opened 2020-09-18 15:17 UTC
There is a script **add_device_to_static.py** which adds an already discovered server to a group. Can this script be enhanced so that the server is discovered and then added to a group. Also the script should have an option to delete a server from a group.

**Comment by grantcurell** [comment] 2020-11-10 17:35
@vmallemp - @RaajeevKalyan may have different thoughts, but I'm not sure it makes sense to do that here. Does the end user just need help tying the two together? We'd have to write a new script that is a verbatim copy and paste of all the code in the two other scripts. Would it be sufficient to provide the functionality for deleting a device somewhere and then they could use that?

**Comment by grantcurell** [comment] 2020-11-24 23:17
Closing since this is a duplicate of #52

**Closed by grantcurell** 2020-11-24 23:17 UTC
Labels: enhancement, help wanted
